### ISSUE TITLE
[Correlation chart] sometimes crashes application

### ISSUE THREAD

**Issue by jfitie** [Vitens/DBM-Desktop#11]
Hard to reproduce, but try opening and closing correlation charts for `ACE-FR-Deelbalansgebied-Leeuwarden-levering` around 1-1-2017 09:15.

**Comment by etrietsch** [comment]
Can not be reproduced. So (possible) bug remains...

**Comment by etrietsch** [comment]
Bug that might have caused these exceptions was caught and removed. So this report will now be closed.
