### ISSUE TITLE
Skip Vitens PI test servers

### ISSUE THREAD

**Issue by jfitie** [Vitens/DBM-Desktop#22]
Do not read tags from Vitens PI test servers.
This would probabaly have to be done in [GetTags()](https://github.com/Vitens/DBM-Desktop/blob/57d0cdb5150d4fcbf3645e23e64d2b7f0b5fe23e/PIDTMNGR/PiDataManager.vb#L111).

**Comment by etrietsch** [comment]
In next version, one can setup the PI servers to exclude from use. (comma or semi-colon seperated), e.g. "sr-25352-t ; sr-32524-t". Also one can set/change de pointsource for the PI DBM tag (e.g. "dbmrt").
