### ISSUE TITLE
Multiple annotations

### ISSUE THREAD

**Issue by jfitie** [Vitens/DBM-Desktop#25]
When multiple days are displayed, a maximum of one annotation is shown for the whole period.
Expected behaviour is to show one annotation per day.
![knipsel](https://cloud.githubusercontent.com/assets/23396293/23461188/30a03fe8-fe89-11e6-8e22-166a86513af0.PNG)

**Comment by etrietsch** [comment]
Bug fixed: if there are multiple annotations then only one is shown.
Feature change: all annotations are shown at their given timestamp.
