### ISSUE TITLE
Calculation until current time instead of last timestamp in PI tag

### ISSUE THREAD

**Issue by jfitie** [Vitens/DBM-Desktop#30]
Data is calculated until the current timestamp. This should be changed to the latest timestamp in the PI tag (snapshot).

![knipsel](https://cloud.githubusercontent.com/assets/23396293/23496515/f3227f8c-ff1e-11e6-8b76-3b63f881b26d.PNG)

**Comment by jfitie** [comment]
@etrietsch, DBM is just the calculator, it has to be told what timestamps to calculate (but will try to calculate any timestamp even if not enough data is available). An example of this logic can be seen in the ACE calculation module. Perhaps this short piece of code can be reused in DBM Desktop?

https://github.com/Vitens/DBM/blob/master/src/PIACENet/DBMRtPIPoint.vb#L93-L109

**Comment by etrietsch** [comment]
When Mohammed won't come to the mountain...
Fixed in next version
