### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by jfitie** [Vitens/DBM-Desktop#39]
Remove '_All rights reserved_' as it is both obsolete and conflicting with the GPL license.

> [The requirement to add the "all rights reserved" notice became essentially obsolete on August 23, 2000, when Nicaragua became the final member of the Buenos Aires Convention to also become a signatory to the Berne Convention. As of that date, every country that was a member of the Buenos Aires Convention (which is the only copyright treaty requiring this notice to be used) was also a member of Berne, which requires protection be granted without any formality of notice of copyright.](https://en.wikipedia.org/wiki/All_rights_reserved)

**Comment by etrietsch** [comment]
solved
