### ISSUE TITLE
Add information to correlation analysis popup

### ISSUE THREAD

**Issue by jfitie** [Vitens/DBM-Desktop#46]
![knipsel](https://cloud.githubusercontent.com/assets/23396293/23989683/b539589c-0a33-11e7-8a71-72010e1d1ca7.PNG)

- Use tag names to label X and Y axes.
- Show angle for both regression lines (`.Angle` and `.OriginAngle`)
- Show correlation coefficient (`.ModifiedCorrelation`) and R^2/determination (`.Determination`).

**Comment by VitDev1** [comment]
Added  in next version

**Comment by jfitie** [comment]
Please add more significant digits (3) to correlation and determination.

**Comment by jfitie** [comment]
Also suggest the following changes:

**Tooltip 1:**

Now:
 _Regr.hoek: -0.5°_

Change to:
 _∠ -0.5°_   <-- Use unicode U+2220
 _r 0.895_   <-- use `DBMStatistics.Correlation`

**Tooltip 2:**

Now:
 _Regr.hoek: 28.9°
 Mod.corr: 0.9
 Determ.: 0.6_

Change to:
 _∠ 28.9°_   <-- Use unicode U+2220
 _rₘ 0.898_   <-- Use unicode U+2098
 _r² 0.565_   <-- Use unicode U+00B2

**Comment by etrietsch** [comment]
changed in new version
