### ISSUE TITLE
Prediction details popup not working

### ISSUE THREAD

**Issue by jfitie** [Vitens/DBM-Desktop#52]
![screenshot from 2017-06-14 09-03-03](https://user-images.githubusercontent.com/23396293/27119472-4d0487c6-50e0-11e7-8989-d848d2cafc68.png)

**Comment by jfitie** [comment]
https://github.com/Vitens/DBM-Desktop/commit/7ea5be95320c82a16ad7c27e70226154a1044595 seems to fix this, mostly.
Please take a look at the chart markers - they're missing from inliers.

![screenshot from 2017-06-19 08-08-41](https://user-images.githubusercontent.com/23396293/27271738-ab5c6c78-54c6-11e7-83b7-b1bd33fbc588.png)

**Comment by etrietsch** [comment]
fixed in new update
