### ISSUE TITLE
Correlation details popup not working

### ISSUE THREAD

**Issue by jfitie** [Vitens/DBM-Desktop#53]
![screenshot from 2017-06-14 09-03-45](https://user-images.githubusercontent.com/23396293/27119513-6c5c3010-50e0-11e7-9009-06e4ba74f1fd.png)

**Comment by etrietsch** [comment]
Could you please provide more details (e.g. which area and date). And is this a reproducable error?

**Comment by etrietsch** [comment]
Is this issue still open? If so, please give some details to produce this error.

**Comment by jfitie** [comment]
Unable to reproduce with current master. Will reopen if needed.
