### ISSUE TITLE
Default calculation parameter values

### ISSUE THREAD

**Issue by jfitie** [Vitens/DBM-Desktop#54]
Default values for calculation parameters are set to hard-coded values in different locations; e.g.:

- https://github.com/Vitens/DBM-Desktop/blob/master/DBM%20GUI/My%20Project/Settings.settings#L17
- https://github.com/Vitens/DBM-Desktop/blob/master/DBM%20GUI/app.config#L45
- https://github.com/Vitens/DBM-Desktop/blob/master/DBM%20GUI/My%20Project/Settings.Designer.vb#L107

Since these default parameters are likely to change in the near feature, and for better maintainability, the default values should come from the ```DBMParameters``` class. https://github.com/Vitens/DBM/blob/master/src/dbm/DBMParameters.vb#L34

**Comment by jfitie** [comment]
- https://github.com/Vitens/DBM-Desktop/blob/master/PIDTMNGR/PiDataManager.vb#L67

**Comment by etrietsch** [comment]
The default paramater values **are** extracted from DBMparameters. The mentioned values are just initializers.

**Comment by jfitie** [comment]
Default values do not seem to come from the ```DBMParameters``` class as shown below.

![screenshot from 2017-06-16 12-21-58](https://user-images.githubusercontent.com/23396293/27222912-8a762844-528e-11e7-932b-732ddda6bac5.png)

For example the ```RegressionAngleRange``` value (https://github.com/Vitens/DBM/blob/master/src/dbm/DBMParameters.vb#L72) should be 18.43494882292201064842780627954670532879578570035477897201... (https://www.wolframalpha.com/input/?i=(Atan(2)%2F(2*PI)*360)-45).
Instead a value with less significant digits is shown, probaby originating at https://github.com/Vitens/DBM-Desktop/blob/master/DBM%20GUI/My%20Project/Settings.Designer.vb#L179 .

**Comment by etrietsch** [comment]
The default values **do** come from DBMparameters.
(see: https://github.com/Vitens/DBM-Desktop/blob/master/DBM%20GUI/DbmDesktop.vb#L169)

How it works: originally all values are extracted from DBMparameters and stored as such until a user changes these settings in the Options form. If you want to see the original values then you could press the reset button which will then on the fly extract the default settings (again) from DBMparameters.

For the example parameter RegressionAngleRange, the value 18,434948822922 is shown when pressing reset. So this is in my opinion what to expect with double precision.

**Comment by jfitie** [comment]
OK, so let's split this issue in two parts;

- The settings dialog might be counterintuitive in that parameter values shown are not the values currently used in the DBM calculations per se. If default parameters in DBM change, they are apparantly used for calculations, but are not correctly shown to the end user in the settings dialog. There should be no need for an end user to have to press an extra button to see currently used parameter values.

- There should be no copies of default parameter values in the code, as linked in the first and second comment in this thread. See key point mentioned in the fourth comment. Why not set the default values to zero as they are overridden by values in the ```DBMParameters``` class on application startup?

Do you agree?

**Comment by jfitie** [comment]
The above is fixed in PR https://github.com/Vitens/DBM-Desktop/pull/77

**Comment by jfitie** [comment]
Merged
https://github.com/Vitens/DBM-Desktop/blob/71ff948ab8f1585dc9a6123a253637b214588d53/PIDTMNGR/PiDataManager.vb#L68
